// Portfolio data for static export - GitHub Pages compatible
// Consolidated portfolio data - single source of truth
// Edit this file directly to make changes to portfolio content

import { PortfolioData } from '../../src/types/portfolio';

export const portfolioData: PortfolioData = {
  "timeline": [
    {
      "id": "cadmium-telluride-impact-2019",
      "title": "Growth and Characterization of Cadmium Telluride and Its Societal, Economic, and Environmental Impact",
      "company": "",
      "location": "Volume 1, Issue 2",
      "date": "October 2019",
      "range": "October 2019",
      "description": "Comprehensive analysis of cadmium telluride growth processes and characterization techniques, examining the societal, economic, and environmental implications of this critical semiconductor material.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 18,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijfmr.com/research-paper.php?id=22647",
      "subtitle": "International Journal For Multidisciplinary Research",
      "content": "\nThis research provides a comprehensive examination of cadmium telluride (CdTe) growth processes and characterization methodologies, addressing the multifaceted impact of this critical semiconductor material. The study explores advanced growth techniques, material characterization approaches, and evaluates the broader societal, economic, and environmental implications of CdTe applications in modern technology. "
    },
    {
      "id": "electric-bicycle-technology-2020",
      "title": "Advancements in Electric Bicycle Technology",
      "company": "",
      "location": "Volume 6, Issue 5",
      "date": "October 2020",
      "range": "October 2020",
      "description": "Comprehensive review of electric bicycle technology advancements, focusing on system integration, monitoring capabilities, and open-source solutions for sustainable transportation.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 17,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirct.org/viewPaper.php?paperId=2412051",
      "subtitle": "A Comprehensive Review of Systems, Monitoring, and Open Source Solutions",
      "content": "\nThis comprehensive review examines the latest advancements in electric bicycle technology, with particular focus on system integration, monitoring capabilities, and open-source solutions. The research addresses critical aspects of e-bike development including battery management systems, motor efficiency, and user interface design, contributing to the advancement of sustainable transportation technologies. "
    },
    {
      "id": "human-robot-interaction-2021",
      "title": "Advances in Human-Robot Interaction",
      "company": "",
      "location": "Volume 9, Issue 5",
      "date": "October 2021",
      "range": "October 2021",
      "description": "Systematic review examining advances in human-robot interaction, focusing on intuitive interface design and communication modalities that enhance user experience and system effectiveness.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 16,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirmps.org/research-paper.php?id=231851",
      "subtitle": "A Systematic Review of Intuitive Interfaces and Communication Modalities",
      "content": "\nThis systematic review examines the latest advances in human-robot interaction, with particular emphasis on intuitive interface design and communication modalities. The research analyzes emerging approaches to enhance user experience and system effectiveness, addressing critical aspects of natural human-robot communication and interface design that bridge the gap between human cognition and robotic systems. "
    },
    {
      "id": "robotics-stem-education-2021",
      "title": "Advancing Robotics-Enabled STEM Education in K-12",
      "company": "",
      "location": "Volume 5, Issue 12",
      "date": "December 2021",
      "range": "December 2021",
      "description": "Comprehensive research examining frameworks for implementing robotics-enabled STEM education in K-12 environments. Focuses on developing inclusive assessment methodologies and ensuring equitable access to robotics education across diverse student populations.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 15,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://ijsrem.com/download/advancing-robotics-enabled-stem-education-in-k-12-frameworks-for-comprehensive-learning-outcomes-assessment-and-inclusivity/",
      "subtitle": "Frameworks for Comprehensive Learning Outcomes Assessment and Inclusivity",
      "content": "\nThis research develops comprehensive frameworks for advancing robotics-enabled STEM education in K-12 environments, with particular emphasis on creating inclusive learning experiences and robust assessment methodologies. The study addresses critical gaps in educational robotics implementation, proposing evidence-based approaches to ensure equitable access and meaningful learning outcomes across diverse student populations.\n"
    },
    {
      "id": "iot-smart-agriculture-2022",
      "title": "A Comprehensive Review of User-Centric Design in IoT Prototyping for Smart Agriculture",
      "company": "",
      "location": "Volume 10, Issue 2",
      "date": "March 2022",
      "range": "March 2022",
      "description": "Comprehensive review of user-centric design approaches in IoT prototyping for smart agriculture, focusing on integrating user feedback in hardware and software development for farming applications.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 14,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirmps.org/research-paper.php?id=231743",
      "subtitle": "Integrating User Feedback in Hardware and Software Development",
      "content": "\nThis comprehensive review examines user-centric design approaches in IoT prototyping for smart agriculture applications, with particular focus on integrating user feedback throughout hardware and software development processes. The research addresses critical aspects of farmer-centered design, usability considerations, and iterative development methodologies that enhance the effectiveness of smart farming technologies.\n"
    },
    {
      "id": "smart-shop-tools-prototyping-2022",
      "title": "Rapid Prototyping Methodologies for Smart Shop Tools",
      "company": "",
      "location": "Volume 1, Issue 1",
      "date": "March 2022",
      "range": "March 2022",
      "description": "Research on rapid prototyping methodologies for smart shop tools, integrating IoT, AI, and user-centered design principles in engineering workflows to enhance manufacturing efficiency.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 13,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://urfjournals.org/open-access/rapid-prototyping-methodologies-for-smart-shop-tools-integrating-iot-ai-and-user-centered-design-in-engineering-workflows.pdf",
      "subtitle": "Integrating IoT, AI, and User-Centered Design in Engineering Workflows",
      "content": "\nThis research develops comprehensive methodologies for rapid prototyping of smart shop tools, integrating Internet of Things (IoT), artificial intelligence (AI), and user-centered design principles within engineering workflows. The study addresses the critical need for intelligent manufacturing tools that enhance productivity while maintaining user-friendly interfaces and efficient operational processes. "
    },
    {
      "id": "haptic-feedback-mixed-reality-2023",
      "title": "Leveraging Haptic Feedback in Mixed Reality",
      "company": "",
      "location": "Volume 5, Issue 4",
      "date": "July 2023",
      "range": "July 2023",
      "description": "Research on leveraging haptic feedback in mixed reality environments to enhance training effectiveness, skill acquisition, and robotic simulation capabilities.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 12,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.onlinescientificresearch.com/articles/leveraging-haptic-feedback-in-mixed-reality-enhancing--training-skill-acquisition-and-robotic-simulation.pdf",
      "subtitle": "Enhancing Training, Skill Acquisition, and Robotic Simulation",
      "content": "\nThis research explores the integration of haptic feedback technology in mixed reality environments to enhance training effectiveness, skill acquisition, and robotic simulation capabilities. The study addresses the critical role of tactile feedback in immersive learning experiences, examining how haptic technologies can bridge the gap between virtual and physical interactions in educational and professional training contexts. "
    },
    {
      "id": "additive-manufacturing-frameworks-2023",
      "title": "Rapid Prototyping Technologies and Design Frameworks",
      "company": "",
      "location": "Volume 4, Issue 1",
      "date": "January 2023",
      "range": "January 2023",
      "description": "Research on rapid prototyping technologies and design frameworks that transform traditional manufacturing processes into intelligent additive solutions.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 11,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.onlinescientificresearch.com/articles/rapid-prototyping-technologies-and-design-frameworks-transforming-traditional-manufacturing-into-smart-additive-solutions.pdf",
      "subtitle": "Transforming Traditional Manufacturing into Smart Additive Solutions",
      "content": "\nThis research examines rapid prototyping technologies and design frameworks that facilitate the transformation of traditional manufacturing processes into intelligent additive solutions. The study addresses critical aspects of smart manufacturing, including advanced material processing, automated design workflows, and integration of digital technologies to enhance manufacturing efficiency and product quality. "
    },
    {
      "id": "sensor-fusion-robotics-2023",
      "title": "Integrating Advanced Sensor Fusion with User-Centered Design and Rapid Prototyping in Robotics",
      "company": "",
      "location": "Volume 2, Issue 9",
      "date": "September 2023",
      "range": "September 2023",
      "description": "Comprehensive review of integrating advanced sensor fusion technologies with user-centered design and rapid prototyping methodologies in robotics systems.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 10,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://isjem.com/download/integrating-advanced-sensor-fusion-with-user-centered-design-and-rapid-prototyping-in-robotics-a-comprehensive-review/",
      "subtitle": "A Comprehensive Review",
      "content": "\nThis comprehensive review examines the integration of advanced sensor fusion technologies with user-centered design principles and rapid prototyping methodologies in robotics systems. The research addresses critical aspects of multi-sensor integration, human-robot interaction design, and accelerated development processes that enhance robotic system effectiveness and user experience. "
    },
    {
      "id": "wsu-honors-global-competition-2017",
      "title": "International Programs Vice President Highlights Global Case Competition",
      "company": "",
      "location": "Student Achievements",
      "date": "December 2017",
      "range": "December 2017",
      "description": "Featured article highlighting participation in global case competition and international programs leadership roles at Washington State University.",
      "category": "Media & Press",
      "type": "media",
      "icon": "TrophyIcon",
      "order": 10,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://honors.wsu.edu/2017/12/11/international-programs-vice-president-highlights-global-case-competition/",
      "subtitle": "WSU Honors Program Feature",
      "content": "\nThis feature article highlights achievements in international programs and global case competition participation at Washington State University. The piece showcases leadership roles in international academic initiatives and competitive case study competitions that demonstrate problem-solving abilities and global perspective in engineering and business applications. "
    },
    {
      "id": "telemedicine-adaptive-ux-2024",
      "title": "Advancing Telemedicine Through Adaptive UX",
      "company": "",
      "location": "Volume 8, Issue 4",
      "date": "August 2024",
      "range": "August 2024",
      "description": "Systematic review examining adaptive user experience design in telemedicine, focusing on interface design for equity and accessibility across diverse healthcare settings.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 9,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.promedsci.org/articles/Advancing%20Telemedicine%20Through%20Adaptive%20UX%20%20A%20Systematic%20Review%20of%20Interface%20Design%20for%20Equity%20and%20Accessibility%20in%20Diverse%20Healthcare%20Settings",
      "subtitle": "A Systematic Review of Interface Design for Equity and Accessibility in Diverse Healthcare Settings",
      "content": "\nThis systematic review examines adaptive user experience design in telemedicine applications, with particular focus on interface design strategies that promote equity and accessibility across diverse healthcare settings. The research addresses critical aspects of inclusive design, cultural sensitivity, and accessibility considerations that ensure effective telemedicine delivery to underserved populations. "
    },
    {
      "id": "wsu-vcea-student-spotlight-2018",
      "title": "Student Spotlight: Parth Chandak",
      "company": "",
      "location": "Student Features",
      "date": "May 2018",
      "range": "May 2018",
      "description": "Student spotlight feature highlighting academic achievements and engineering contributions at Washington State University Voiland College of Engineering and Architecture.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 9,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/2018/05/24/parth-chandak/",
      "subtitle": "VCEA Featured Student",
      "content": "\nThis student spotlight feature showcases academic achievements and engineering contributions at Washington State University's Voiland College of Engineering and Architecture. The article highlights research activities, leadership roles, and academic excellence in engineering disciplines, demonstrating commitment to innovation and scholarly pursuits in engineering education. "
    },
    {
      "id": "cleanroom-workbench-design-assembly",
      "title": "Cleanroom Workbench Design and Assembly",
      "company": "",
      "location": "",
      "date": "2016",
      "range": "2016",
      "description": "Design and assembly of specialized workbench for Class 1000 cleanroom environment, ensuring contamination control and precision manufacturing capabilities.",
      "category": "Engineering Design",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 9,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/engineering-design",
      "image": "project-photos/cleanroom-workbench-design-assembly.png",
      "subtitle": "Class 1000 Cleanroom Environment",
      "content": "\nSystems design project focused on developing a Class 1000 cleanroom workbench with client-specified modules. The project emphasized engineering different paradigms and utilizing LEAN manufacturing techniques to personalize each workbench while minimizing waste through efficient design and manufacturing processes. "
    },
    {
      "id": "healthcare-iot-prototyping-2024",
      "title": "Systematic Review of Healthcare IoT and Rapid Prototyping Applications",
      "company": "",
      "location": "Volume 8, Issue 4",
      "date": "August 2024",
      "range": "August 2024",
      "description": "Systematic review of healthcare IoT and rapid prototyping applications, addressing implementation challenges and development strategies for healthcare technology solutions.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 8,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.promedsci.org/articles/Systematic%20Review%20of%20Healthcare%20IoT%20and%20Rapid%20Prototyping%20Applications%20%20Addressing%20Challenges%20and%20Implementation",
      "subtitle": "Addressing Challenges and Implementation",
      "content": "\nThis systematic review examines healthcare IoT and rapid prototyping applications, addressing critical implementation challenges and development strategies for healthcare technology solutions. The research focuses on identifying best practices for IoT integration in healthcare settings and rapid prototyping methodologies that accelerate medical device development while ensuring safety and efficacy. "
    },
    {
      "id": "human-robot-interaction-interview-2022",
      "title": "Advancing Human-Robot Interaction Through Intuitive Interfaces",
      "company": "",
      "location": "Technology Section",
      "date": "March 2022",
      "range": "March 2022",
      "description": "Interview discussing advancements in human-robot interaction through intuitive interfaces and multi-modal feedback systems, based on published research in communication modalities.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 8,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirmps.org/research-paper.php?id=231851",
      "subtitle": "Interview: Multi-Modal Feedback Systems",
      "content": "\nThis interview explores the cutting-edge developments in human-robot interaction, focusing on intuitive interface design and multi-modal feedback systems. The discussion covers systematic approaches to improving communication between humans and robots, drawing from comprehensive research on interface design and communication modalities that enhance user experience and system effectiveness. "
    },
    {
      "id": "engineering-gear-system-parallax-bot",
      "title": "Engineering Gear System for Parallax Bot",
      "company": "",
      "location": "",
      "date": "2016",
      "range": "2016",
      "description": "Engineering project involving the design and fabrication of gear systems for Parallax Bot using advanced 3D printing and laser cutting techniques.",
      "category": "Engineering Design",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 8,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.parallax.com/product/boe-bot-robot",
      "image": "project-photos/engineering-gear-system-parallax-bot.png",
      "subtitle": "3D Printing & Laser Cutting",
      "content": "\nAdvanced prototype manufacturing project focused on designing and manufacturing a gear system for the Parallax Boe Bot used in the ENGR120 class at Washington State University. Successfully engineered a solution to increase the robot's speed by 2-6 times while maintaining the integrity of the original frame and mounting holes using 3D printing and laser cutting techniques. "
    },
    {
      "id": "arth-systems-marketing-intern",
      "title": "Marketing Intern",
      "company": "Arth Systems",
      "location": "Redmond, WA",
      "date": "May 2015 - Nov 2015",
      "range": "May 2015 - Nov 2015",
      "description": "Newsletter drafting and editing. Contributed to marketing initiatives and content creation for technology solutions.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 7,
      "technologies": [],
      "tags": [
        {
          "name": "Team Building",
          "icon": "TbUsersPlus",
          "category": "Team"
        },
        {
          "name": "Leadership Development",
          "icon": "TbUserShield",
          "category": "Team"
        },
        {
          "name": "Google Suite",
          "icon": "SiGoogle",
          "category": "Project Management"
        }
      ],
      "color": "#E53E3E",
      "link": "https://arthsystems.com",
      "iconOverride": "company-logos/arth-systems-logo.png",
      "content": ""
    },
    {
      "id": "ai-health-assistants-2024",
      "title": "Ethical, Governance, and Usability Challenges in AI-Powered Virtual Health Assistants",
      "company": "",
      "location": "Volume 7, Issue 1",
      "date": "January 2025",
      "range": "January 2025",
      "description": "Systematic thematic analysis examining ethical, governance, and usability challenges in AI-powered virtual health assistants, addressing critical concerns in healthcare AI implementation.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 7,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijfmr.com/research-paper.php?id=39043",
      "subtitle": "A Systematic Thematic Analysis",
      "content": "\nThis systematic thematic analysis examines the ethical, governance, and usability challenges associated with AI-powered virtual health assistants in healthcare settings. The research addresses critical concerns including data privacy, algorithmic bias, regulatory compliance, and user experience design, providing comprehensive insights into responsible AI implementation in healthcare applications.\n"
    },
    {
      "id": "indiahood-rapid-prototyping-2023",
      "title": "Rapid Prototyping Methodologies for Complex Systems",
      "company": "",
      "location": "Technology Section",
      "date": "June 2023",
      "range": "June 2023",
      "description": "In-depth interview exploring rapid prototyping methodologies for complex systems, covering the journey from initial concept through comprehensive testing phases.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 7,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://indiahood.com/interview-rapid-prototyping-methodologies-for-complex-systems-from-concept-to-testing/",
      "subtitle": "From Concept to Testing",
      "content": "\nThis comprehensive interview delves into advanced rapid prototyping methodologies for complex systems, exploring the complete development lifecycle from initial concept through rigorous testing phases. The discussion covers innovative approaches to smart manufacturing, additive solutions, and the integration of IoT, AI, and user-centered design principles in engineering workflows. "
    },
    {
      "id": "swordmaking-katanas-material-science",
      "title": "Swordmaking: Katanas",
      "company": "",
      "location": "",
      "date": "2016",
      "range": "2016",
      "description": "In-depth material science analysis of katana sword construction, examining metallurgical properties, heat treatment processes, and traditional forging techniques.",
      "category": "Material Science",
      "type": "project",
      "icon": "RocketLaunchIcon",
      "order": 7,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/school-of-mechanical-and-materials-engineering",
      "image": "project-photos/swordmaking-katanas-material-science.png",
      "subtitle": "Material Science Analysis",
      "content": "\nMaterial science analysis project examining historically prominent swordmaking materials and determining what modern materials would be optimal for creating a katana. This project bridges historical metallurgy with contemporary materials engineering to explore the evolution of sword-making technology and practical applications in modern manufacturing. "
    },
    {
      "id": "robert-finch-memorial-scholarship-2015",
      "title": "Robert W. Finch Memorial Scholarship",
      "company": "",
      "location": "",
      "date": "March 2015",
      "description": "Awarded by the School of Mechanical and Materials Engineering, WSU.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 7,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/school-of-mechanical-and-materials-engineering",
      "subtitle": "School of Mechanical and Materials Engineering, WSU",
      "content": ""
    },
    {
      "id": "wsu-resident-technology-assistant",
      "title": "Resident Technology Assistant",
      "company": "Washington State University",
      "location": "Pullman, WA",
      "date": "Aug 2016 - May 2018",
      "range": "Aug 2016 - May 2018",
      "description": "Delivered standard service and support for technology-based devices in residence halls for 400+ residents. Enforced campus policies regarding network and technology. Created events and organized programs to enrich residents in technology.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 6,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://wsu.edu",
      "iconOverride": "company-logos/washington-state-uni-logo.png",
      "content": ""
    },
    {
      "id": "hans-india-mixed-reality-2024",
      "title": "Leveraging Mixed Reality and Haptic Feedback for Immersive User Experiences",
      "company": "",
      "location": "Technology Section",
      "date": "December 2024",
      "range": "December 2024",
      "description": "In-depth interview exploring the convergence of mixed reality and haptic feedback technologies for creating immersive user experiences. Discusses applications in training, skill acquisition, and robotic simulation based on published research.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 6,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.thehansindia.com/business/leveraging-mixed-reality-and-haptic-feedback-for-immersive-user-experiences-926474",
      "subtitle": "The Hans India",
      "content": "\nThis comprehensive interview delves into the cutting-edge intersection of mixed reality and haptic feedback technologies, exploring how their convergence creates unprecedented immersive user experiences. The discussion covers practical applications in professional training environments, skill acquisition programs, and advanced robotic simulation systems, drawing insights from extensive research in haptic feedback systems and mixed reality interface design.\n"
    },
    {
      "id": "user-centered-design-rapid-prototyping-2024",
      "title": "Systematic Review of Integrating User-Centered Design Principles in Rapid Robotic System Prototyping",
      "company": "",
      "location": "Volume 12, Issue 4",
      "date": "August 2024",
      "range": "August 2024",
      "description": "Systematic review examining the integration of user-centered design principles in rapid robotic system prototyping, focusing on methodologies that enhance user experience and system effectiveness.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 6,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirmps.org/research-paper.php?id=231741",
      "subtitle": "International Journal of Innovative Research in Engineering and Management",
      "content": "\nThis systematic review examines the integration of user-centered design principles in rapid robotic system prototyping, addressing critical methodologies that enhance user experience and system effectiveness. The research provides comprehensive insights into design approaches that bridge human-centered design with rapid prototyping technologies in robotics applications. "
    },
    {
      "id": "acrt-furnace-safety-research",
      "title": "Research: A Take on Safety",
      "company": "",
      "location": "",
      "date": "2016",
      "range": "2016",
      "description": "Research project focused on safety considerations in ACRT (Accelerated Crucible Rotation Technique) furnace system design, examining safety protocols and risk mitigation strategies.",
      "category": "Research & Development",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 6,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/research",
      "image": "project-photos/acrt-furnace-safety-research.png",
      "subtitle": "ACRT Furnace System Design",
      "content": "\nResearch project focused on safety analysis and system design for Accelerated Crucible Rotation Technique (ACRT) furnaces. The project involved comprehensive design, manufacturing, and testing of safety systems using SolidWorks and advanced manufacturing techniques to enhance safety protocols for furnace operations. "
    },
    {
      "id": "honor-roll-2015",
      "title": "Honor Roll",
      "company": "",
      "location": "",
      "date": "August 2015",
      "description": "Awarded by Associated Students of Washington State University (ASWSU). Reaching one of the highest levels of academic excellence - the Presidents Honor Roll.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 6,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://wsu.edu",
      "subtitle": "Associated Students of Washington State University (ASWSU)",
      "content": ""
    },
    {
      "id": "boeing-scholar",
      "title": "Boeing Scholar",
      "company": "Boeing Company",
      "location": "Seattle, WA",
      "date": "May 2017 - Aug 2017",
      "range": "May 2017 - Aug 2017",
      "description": "Boeing Scholar program participant focusing on aerospace engineering research and advanced computational methods for aircraft systems analysis.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 5,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://boeing.com",
      "iconOverride": "company-logos/boeing-logo.png",
      "subtitle": "Boeing Company",
      "content": ""
    },
    {
      "id": "analytics-insight-manufacturing-2025",
      "title": "User-Centered Design Approaches for Manufacturing Systems",
      "company": "",
      "location": "",
      "date": "March 2025",
      "description": "Featured interview published in Analytics Insight discussing innovative approaches to implementing user-centered design principles in manufacturing systems. The article explores how human-centered design methodologies can improve efficiency, safety, and worker satisfaction in industrial environments.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 5,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.analyticsinsight.net/manufacturing/user-centered-design-approaches-for-manufacturing-systems",
      "content": " "
    },
    {
      "id": "haptic-feedback-evolution-2024",
      "title": "The Evolution of Haptic Feedback Systems and the Impact of User Experience",
      "company": "",
      "location": "Volume 12, Issue 6",
      "date": "November 2024",
      "range": "November 2024",
      "description": "Literature review examining the evolution of haptic feedback systems and their impact on user experience across various applications and industries.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 5,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijirmps.org/research-paper.php?id=231735",
      "subtitle": "A Literature Review",
      "content": "\nThis literature review examines the evolution of haptic feedback systems and their significant impact on user experience across various applications and industries. The research provides comprehensive insights into the development of tactile technologies, user interaction paradigms, and the role of haptic feedback in enhancing human-computer interaction across diverse domains.\n"
    },
    {
      "id": "green-fridge-entrepreneurship",
      "title": "Green Fridge: Energy-Efficient Cooling Solutions",
      "company": "",
      "location": "",
      "date": "2017",
      "range": "2017",
      "description": "Innovative energy-efficient refrigeration system designed for entrepreneurship competition, focusing on sustainable cooling technologies and reduced environmental impact.",
      "category": "Innovation & Entrepreneurship",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 5,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/undergraduate-programs/entrepreneurship",
      "image": "project-photos/green-fridge-entrepreneurship.png",
      "subtitle": "Entrepreneurship Competition Project",
      "content": "\nLed a multidisciplinary team at the Harold Frank Engineering Entrepreneurship Institute to develop a comprehensive business plan for an innovative sustainable refrigeration system integrated with intelligent food tracking capabilities. The project combined environmental sustainability analysis with practical software development, creating both hardware specifications for energy-efficient refrigeration and a complementary Android application for food waste reduction and inventory management.\n"
    },
    {
      "id": "international-merit-award-2015",
      "title": "International Merit Award",
      "company": "",
      "location": "",
      "date": "August 2015",
      "description": "Awarded to international students studying at WSU for outstanding academic performance.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 5,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://wsu.edu",
      "subtitle": "Washington State University",
      "content": ""
    },
    {
      "id": "berg-engineering-assistant",
      "title": "Engineering Assistant",
      "company": "Berg, LLC",
      "location": "Spokane, WA",
      "date": "June 2017 - Aug 2017",
      "range": "June 2017 - Aug 2017",
      "description": "Engineering assistant role focusing on technical support, project coordination, and engineering documentation for infrastructure projects.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 4,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://berg.wsu.edu",
      "iconOverride": "company-logos/berg-logo.png",
      "subtitle": "Berg, LLC",
      "content": ""
    },
    {
      "id": "deccan-chronicle-2024",
      "title": "The Creative Technologist: Bridging Engineering, UX, and Robotics",
      "company": "",
      "location": "Technology Section",
      "date": "April 2025",
      "range": "April 2025",
      "description": "Career-focused interview discussing the evolving role of creative technologists in bridging engineering, user experience design, and robotics across diverse industries.",
      "category": "Media & Press",
      "type": "media",
      "icon": "BriefcaseIcon",
      "order": 4,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.deccanchronicle.com/general/the-creative-technologist-bridging-engineering-ux-and-robotics-1875816",
      "subtitle": "Career Interview",
      "content": "\nThis career-focused interview explores the evolving role of creative technologists in modern industry, examining how professionals bridge the gap between engineering, user experience design, and robotics. The discussion covers the unique skill sets required, career pathways, and the impact of creative technologists in driving innovation across diverse sectors including autonomous systems, manufacturing, and healthcare technology.\n"
    },
    {
      "id": "bio-inspired-phototropic-materials-2024",
      "title": "Optimizing Bio-Inspired Phototropic Materials",
      "company": "",
      "location": "Volume 2, Issue 4",
      "date": "November 2024",
      "range": "November 2024",
      "description": "Research on optimizing bio-inspired phototropic materials to address scalability and durability challenges for passive solar tracking systems, examining innovative approaches to sustainable energy solutions.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 4,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.espjournals.org/IJACT/ijact-v2i4p113",
      "subtitle": "Addressing Scalability and Durability Challenges for Passive Solar Tracking Systems",
      "content": "\nThis research examines the optimization of bio-inspired phototropic materials to address critical scalability and durability challenges in passive solar tracking systems. The study explores innovative approaches to sustainable energy solutions, focusing on material science advancements that enhance the efficiency and longevity of solar tracking technologies inspired by natural phototropic mechanisms. "
    },
    {
      "id": "microprocessor-programming-complex-signals",
      "title": "Microprocessor Programming for Transmission of Complex Signals",
      "company": "",
      "location": "",
      "date": "2017",
      "range": "2017",
      "description": "Worked with Abhishek Ganarappu & Shrunga Malavalli on mobile app development platform for a research team led by Dr. Arda Gozen at WSU.",
      "category": "Projects",
      "type": "project",
      "icon": "RocketLaunchIcon",
      "order": 4,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://os.mbed.com/platforms/mbed-LPC1768",
      "image": "project-photos/microprocessor-programming-complex-signals.png",
      "subtitle": "Testing on mbed LPC 1768",
      "content": "\nAdvanced microprocessor programming project focused on developing systems for transmitting complex signals using the mbed LPC 1768 platform. Collaborated with research team members on creating mobile app development platform integration under the supervision of Dr. Arda Gozen at Washington State University. "
    },
    {
      "id": "guy-thornton-engineering-scholarship-2016",
      "title": "Guy E. Thornton Engineering Scholarship",
      "company": "",
      "location": "",
      "date": "August 2016",
      "description": "Awarded by the School of Mechanical and Materials Engineering, WSU.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 4,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/school-of-mechanical-and-materials-engineering",
      "subtitle": "School of Mechanical and Materials Engineering, WSU",
      "content": ""
    },
    {
      "id": "tesla-engineering-intern",
      "title": "Engineering Intern",
      "company": "Tesla",
      "location": "Fremont, CA",
      "date": "May 2018 - Aug 2018",
      "range": "May 2018 - Aug 2018",
      "description": "VBA & PowerQuery logistic trip planning for truck charging program (2000+ mile trips). Designed & built model library of 20+ Supercharger components for architecture & engineering firms. Civil/architectural site design for next-generation Superchargers in Google SketchUp.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://tesla.com",
      "iconOverride": "company-logos/tesla-logo.png",
      "content": ""
    },
    {
      "id": "midday-healthcare-technology-2025",
      "title": "User-Centered Design Principles in Healthcare Technology: Lessons for Autonomous Systems",
      "company": "",
      "location": "",
      "date": "April 2025",
      "description": "Featured interview in Mid-Day exploring the intersection of user-centered design principles in healthcare technology and their applications to autonomous systems. The article discusses how lessons learned from healthcare UX design can be applied to improve the development of autonomous vehicle interfaces.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.mid-day.com/buzz/article/user-centered-design-principles-in-healthcare-technology-parallels-with-autonomous-systems-5654",
      "content": " "
    },
    {
      "id": "healthcare-education-youth-2025",
      "title": "User-Centered Design and Rapid Prototyping in Healthcare Education Technologies for Youth",
      "company": "",
      "location": "Volume 9, Issue 1",
      "date": "January 2025",
      "range": "January 2025",
      "description": "Systematic review examining user-centered design and rapid prototyping methodologies in healthcare education technologies specifically designed for youth populations.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.promedsci.org/articles/User-Centered%20Design%20and%20Rapid%20Prototyping%20in%20Healthcare%20Education%20Technologies%20for%20Youth%20%20A%20Systematic%20Review",
      "subtitle": "A Systematic Review",
      "content": "\nThis systematic review examines user-centered design and rapid prototyping methodologies in healthcare education technologies specifically designed for youth populations. The research addresses critical aspects of age-appropriate design, engagement strategies, and educational effectiveness in digital health literacy programs for young people. "
    },
    {
      "id": "rebuilding-together-2023",
      "title": "Rebuilding Together",
      "company": "",
      "location": "",
      "date": "April 2023",
      "description": "Re-did the entire yard, removed grass, laid down over 200 lbs of crushed gravel, worked on house interiors, installed rails, and cleaned up the backyard.",
      "category": "Community Service",
      "type": "community",
      "icon": "UsersIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://rebuildingtogether.org",
      "subtitle": "Community Volunteer",
      "content": ""
    },
    {
      "id": "audio-analyzing-software",
      "title": "Audio Analyzing Software",
      "company": "",
      "location": "",
      "date": "2017",
      "range": "2017",
      "description": "Advanced audio analysis software utilizing Python and MATLAB for Fast Fourier Transform (FFT) analysis, enabling detailed frequency domain analysis of audio signals.",
      "category": "Software Development",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://crimsoncode.wsu.edu",
      "image": "project-photos/audio-analyzing-software.png",
      "subtitle": "Python & MATLAB FFT Analysis",
      "content": "\nSoftware engineering project developed during the Crimson Code Software Hackathon at Washington State University. Created advanced audio analysis software using Python and MATLAB that analyzes audio using Fast Fourier Transforms (FFTs) and modifies audio tone based on user preferences. The software has practical applications in the film industry, allowing audiences to customize audio intensity according to their preferences. "
    },
    {
      "id": "housing-dining-advisory-board-2016",
      "title": "Housing and Dining Advisory Board Certificate of Appreciation",
      "company": "",
      "location": "",
      "date": "December 2016",
      "description": "Board Member for Housing and Dining Finance Committee at WSU. Helped in discussing a budget of over 7 million USD and voice the student opinion.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 3,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://wsu.edu",
      "subtitle": "Washington State University",
      "content": ""
    },
    {
      "id": "free-press-journal-autonomous-systems-2025",
      "title": "Bridging the Trust Gap Between Humans and Autonomous Systems Through Intuitive Interfaces",
      "company": "",
      "location": "Technology Section",
      "date": "May 2025",
      "range": "May 2025",
      "description": "Featured interview discussing innovative approaches to building trust between humans and autonomous systems through intuitive interface design. Explores the intersection of UX design and autonomous vehicle technology at Zoox.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 2,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.freepressjournal.in/latest-news/bridging-the-trust-gap-between-humans-autonomous-systems-through-intuitive-interfaces",
      "subtitle": "Free Press Journal",
      "content": "\nThis comprehensive interview explores cutting-edge approaches to bridging the critical trust gap between humans and autonomous systems. The article delves into innovative interface design methodologies that enhance user confidence in autonomous vehicle technology, drawing from real-world experience at Zoox developing next-generation transportation interfaces.\n"
    },
    {
      "id": "ai-health-assistants-2025",
      "title": "Ethical, Governance, and Usability Challenges in AI-Powered Virtual Health Assistants",
      "company": "",
      "location": "Volume 7, Issue 1",
      "date": "January 2025",
      "range": "January 2025",
      "description": "Systematic thematic analysis examining ethical, governance, and usability challenges in AI-powered virtual health assistants, addressing critical concerns in healthcare AI implementation.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 2,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijfmr.com/research-paper.php?id=39043",
      "subtitle": "A Systematic Thematic Analysis",
      "content": "\nThis systematic thematic analysis examines the ethical, governance, and usability challenges associated with AI-powered virtual health assistants in healthcare settings. The research addresses critical concerns including data privacy, algorithmic bias, regulatory compliance, and user experience design, providing comprehensive insights into responsible AI implementation in healthcare applications.\n"
    },
    {
      "id": "catholic-worker-house-2023",
      "title": "Catholic Worker House",
      "company": "",
      "location": "",
      "date": "October 2023",
      "description": "Painted the kitchen, built shelves in the food and tool sheds, and refurbished the landscaping.",
      "category": "Community Service",
      "type": "community",
      "icon": "UsersIcon",
      "order": 2,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://catholicworker.org",
      "subtitle": "Community Volunteer",
      "content": " "
    },
    {
      "id": "boeing-damping-ratios",
      "title": "Boeing 737 Damping Ratios Analysis",
      "company": "",
      "location": "",
      "date": "2018",
      "range": "2018",
      "description": "Comprehensive damping ratios analysis for Boeing 737 aircraft systems, examining structural dynamics and vibration characteristics.",
      "category": "Engineering Projects",
      "type": "projects",
      "icon": "RocketLaunchIcon",
      "order": 2,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://boeing.com/innovation/research-technology",
      "image": "project-photos/boeing-damping-ratios.png",
      "subtitle": "Engineering Analysis Project",
      "content": "\nCollaborated with Boeing mentor Arun Nadkarni on a critical aerospace engineering research project aimed at optimizing aircraft performance through advanced vibration analysis. The project focused on developing computational methods for accurately determining damping ratios of low frequency vibration modes in piloted aircraft systems, with the primary goal of significantly reducing required test flight time while maintaining safety and performance standards.\n"
    },
    {
      "id": "harold-frank-fellows-2017",
      "title": "Harold Frank Fellows Kauffman Award",
      "company": "",
      "location": "",
      "date": "January 2017",
      "description": "Recognized for innovation and entrepreneurial spirit in engineering.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 2,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://vcea.wsu.edu/harold-frank-fellows",
      "subtitle": "Harald Frank Engineering Entrepreneurship Institute",
      "content": ""
    },
    {
      "id": "zoox-creative-technologist",
      "title": "Creative Technologist",
      "company": "Zoox",
      "location": "Foster City, CA",
      "date": "Jan 2022 - Present",
      "range": "Jan 2022 - Present",
      "description": "Led creation of UX-focused robot for 10+ visual & sonic experience projects. Created 15+ electro-mechanical & software (Python, C++, React) prototypes, enhancing research & design studies for autonomous vehicle user experiences.",
      "category": "Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 1,
      "technologies": [],
      "tags": [
        {
          "name": "Python",
          "icon": "SiPython",
          "category": "technical"
        },
        {
          "name": "React",
          "icon": "SiReact",
          "category": "technical"
        },
        {
          "name": "C++",
          "icon": "SiCplusplus",
          "category": "technical"
        },
        {
          "name": "SolidWorks",
          "icon": "TbCube",
          "category": "technical"
        },
        {
          "name": "User Experience Design",
          "icon": "TbUserHeart",
          "category": "experience"
        },
        {
          "name": "Autonomous Vehicles",
          "icon": "TbCar",
          "category": "experience"
        },
        {
          "name": "Hardware Development",
          "icon": "TbCircuitCell",
          "category": "experience"
        },
        {
          "name": "Innovation",
          "icon": "TbBulb",
          "category": "research"
        }
      ],
      "color": "#E53E3E",
      "link": "https://zoox.com",
      "iconOverride": "company-logos/zoox-logo.png",
      "content": ""
    },
    {
      "id": "zoox-manufacturing-engineer",
      "title": "Manufacturing Engineer",
      "company": "Zoox",
      "location": "Foster City, CA",
      "date": "August 2022 - Present",
      "range": "August 2022 - Present",
      "description": "Manufacturing Engineer at Zoox developing autonomous vehicle production systems and advanced manufacturing processes for next-generation mobility solutions. Designed 3+ mechanical assembly fixtures for hardware installation & test automation. Created work-order system for 40+ technicians that aided 2x growth in manufacturing, quality, testing & material workflows. Manufactured autonomous vehicle hardware for 10+ products from DFMEA to OQC.",
      "category": "Professional Experience",
      "type": "experience",
      "icon": "BriefcaseIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://zoox.com",
      "iconOverride": "company-logos/zoox-logo.png",
      "content": ""
    },
    {
      "id": "outlook-electric-transport-2025",
      "title": "Optimizing Data Collection Systems for Next-Generation Electric Transport",
      "company": "",
      "location": "",
      "date": "May 2025",
      "description": "Featured interview in Outlook India discussing innovative approaches to optimizing data collection systems for next-generation electric transport. The article explores insights gained from work at Tesla on charging infrastructure and data analytics for electric vehicle deployment.",
      "category": "Media & Press",
      "type": "media",
      "icon": "FilmIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.outlookindia.com/hub4business/optimizing-data-collection-systems-for-next-generation-electric-transport",
      "content": " "
    },
    {
      "id": "telemedicine-ar-2025",
      "title": "Augmented Reality Enhances Telemedicine Training",
      "company": "",
      "location": "Volume 7, Issue 1",
      "date": "February 2025",
      "range": "February 2025",
      "description": "Systematic review examining the effectiveness and challenges of augmented reality in enhancing telemedicine training, focusing on educational outcomes and implementation considerations.",
      "category": "Research",
      "type": "research",
      "icon": "BeakerIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://www.ijfmr.com/research-paper.php?id=38539",
      "subtitle": "A Systematic Review on Effectiveness and Challenges",
      "content": "\nThis systematic review examines the effectiveness and challenges of augmented reality technologies in enhancing telemedicine training programs. The research addresses critical aspects of AR integration in medical education, analyzing educational outcomes, implementation considerations, and the potential for AR to transform remote healthcare training delivery.\n"
    },
    {
      "id": "rebuilding-together-2024",
      "title": "Rebuilding Together",
      "company": "",
      "location": "",
      "date": "April 2024",
      "description": "Built a fence under Mr. Frank's guidance from the RTP team, installed a new microwave, added a handrail to the bottom stairs leading to the yard, cleared the area, and mowed the grass.",
      "category": "Community Service",
      "type": "community",
      "icon": "UsersIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://rebuildingtogether.org",
      "subtitle": "Community Volunteer",
      "content": " "
    },
    {
      "id": "crimson-code-2018",
      "title": "Crimson Code 2018: Caffeine Cycle",
      "company": "",
      "location": "",
      "date": "2018",
      "description": "Developed a prize-winning application during the Crimson Code hackathon, focusing on robotics and autonomous systems.",
      "category": "Projects",
      "type": "project",
      "icon": "CodeBracketIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://crimsoncode.wsu.edu",
      "image": "project-photos/crimson-code-2018.png",
      "subtitle": "Hackathon Winner",
      "content": ""
    },
    {
      "id": "roty-2017",
      "title": "Resident Technology Assistant of the Year (ROTY)",
      "company": "",
      "location": "",
      "date": "April 2017",
      "description": "Awarded by the Department of Residence Life at the end-of-the-year banquet.",
      "category": "Awards",
      "type": "award",
      "icon": "TrophyIcon",
      "order": 1,
      "technologies": [],
      "tags": [],
      "color": "#E53E3E",
      "link": "https://zoox.com/careers",
      "subtitle": "Department of Residence Life, WSU",
      "content": ""
    }
  ],
  "navigation": [
    {
      "id": "about",
      "label": "About",
      "icon": "UserIcon",
      "section": "about",
      "folder": "00_about",
      "color": "#E53E3E"
    },
    {
      "id": "experience",
      "label": "Experience",
      "icon": "BriefcaseIcon",
      "section": "experience",
      "folder": "01_experience",
      "color": "#E53E3E"
    },
    {
      "id": "projects",
      "label": "Projects",
      "icon": "RocketLaunchIcon",
      "section": "projects",
      "folder": "02_projects",
      "color": "#E53E3E"
    },
    {
      "id": "research",
      "label": "Research",
      "icon": "BeakerIcon",
      "section": "research",
      "folder": "03_research",
      "color": "#E53E3E"
    },
    {
      "id": "awards",
      "label": "Awards",
      "icon": "TrophyIcon",
      "section": "awards",
      "folder": "04_awards",
      "color": "#E53E3E"
    },
    {
      "id": "community",
      "label": "Community",
      "icon": "UsersIcon",
      "section": "community",
      "folder": "05_community",
      "color": "#E53E3E"
    },
    {
      "id": "media",
      "label": "Media",
      "icon": "FilmIcon",
      "section": "media",
      "folder": "06_media",
      "color": "#E53E3E"
    },
    {
      "id": "contact",
      "label": "Contact",
      "icon": "EnvelopeIcon",
      "section": "contact",
      "folder": "07_contact",
      "color": "#E53E3E"
    }
  ],
  "socialMedia": [
    {
      "id": "linkedin",
      "label": "LinkedIn",
      "icon": "linkedin",
      "url": "https://linkedin.com/in/parthchandak02",
      "color": "#0077B5"
    },
    {
      "id": "github",
      "label": "GitHub",
      "icon": "github",
      "url": "https://github.com/parthchandak02",
      "color": "#333"
    },
    {
      "id": "email",
      "label": "Email",
      "icon": "EnvelopeIcon",
      "url": "mailto:parth.chandak02@gmail.com",
      "color": "#EF4444"
    },
    {
      "id": "calendar",
      "label": "Schedule Call",
      "icon": "CalendarDaysIcon",
      "url": "http://tiny.cc/parthchandakbook",
      "color": "#06B6D4"
    },
    {
      "id": "resume",
      "label": "Resume",
      "icon": "DocumentTextIcon",
      "url": "https://tiny.cc/parthchandakresume",
      "color": "#8B5CF6"
    }
  ],
  "tags": {
    "team": [
      {
        "name": "Team Building",
        "icon": "TbUsersPlus"
      },
      {
        "name": "Leadership Development",
        "icon": "TbUserShield"
      }
    ],
    "project_management": [
      {
        "name": "Google Suite",
        "icon": "SiGoogle"
      }
    ],
    "technical": [
      {
        "name": "Python",
        "icon": "SiPython"
      },
      {
        "name": "React",
        "icon": "SiReact"
      },
      {
        "name": "C++",
        "icon": "SiCplusplus"
      },
      {
        "name": "SolidWorks",
        "icon": "TbCube"
      }
    ],
    "experience": [
      {
        "name": "User Experience Design",
        "icon": "TbUserHeart"
      },
      {
        "name": "Autonomous Vehicles",
        "icon": "TbCar"
      },
      {
        "name": "Hardware Development",
        "icon": "TbCircuitCell"
      }
    ],
    "research": [
      {
        "name": "Innovation",
        "icon": "TbBulb"
      }
    ],
    "community": [],
    "media": [],
    "awards": []
  },
  "about": {
    "title": "About",
    "currentPosition": "Creative Technologist at Zoox",
    "location": "Foster City, CA",
    "description": "Creative technologist specializing in cutting-edge human-computer interaction for autonomous vehicles and robotics.",
    "tags": {
      "technical": [
        { "name": "Python", "icon": "SiPython" },
        { "name": "React", "icon": "SiReact" },
        { "name": "C++", "icon": "SiCplusplus" },
        { "name": "SolidWorks", "icon": "TbCube" },
        { "name": "Arduino", "icon": "SiArduino" },
        { "name": "Raspberry Pi", "icon": "SiRaspberrypi" }
      ],
      "project_management": [
        { "name": "Agile", "icon": "TbChartInfographic" },
        { "name": "JIRA", "icon": "SiJira" },
        { "name": "Google Suite", "icon": "SiGoogle" },
        { "name": "Team Leadership", "icon": "TbUserShield" },
        { "name": "Cross-functional Collaboration", "icon": "TbUsersGroup" },
        { "name": "Process Improvement", "icon": "TbArrowsSort" }
      ],
      "research": [
        { "name": "Academic Research", "icon": "TbBook" },
        { "name": "Scientific Writing", "icon": "TbFileText" },
        { "name": "Literature Review", "icon": "TbBooks" },
        { "name": "Experimental Design", "icon": "TbTestPipe" },
        { "name": "User Experience Research", "icon": "TbUserSearch" },
        { "name": "Innovation", "icon": "TbBulb" }
      ],
      "experience": [
        { "name": "Autonomous Vehicles", "icon": "TbCar" },
        { "name": "User Experience Design", "icon": "TbUserHeart" },
        { "name": "Hardware Development", "icon": "TbCircuitCell" },
        { "name": "Manufacturing Engineering", "icon": "TbBuildingFactory" },
        { "name": "Prototyping", "icon": "TbCube" },
        { "name": "Robotics", "icon": "TbRobot" }
      ],
      "community": [
        { "name": "Mentorship", "icon": "TbUserStar" },
        { "name": "Team Building", "icon": "TbUsersPlus" },
        { "name": "Community Service", "icon": "TbHeartHandshake" },
        { "name": "Leadership Development", "icon": "TbUserShield" },
        { "name": "Volunteering", "icon": "TbHandStop" },
        { "name": "Social Impact", "icon": "TbWorld" }
      ],
      "awards": [
        { "name": "Engineering Excellence", "icon": "TbAward" },
        { "name": "Academic Achievement", "icon": "TbSchool" },
        { "name": "Leadership Awards", "icon": "TbMedal" },
        { "name": "Scholarship Recipient", "icon": "TbCertificate" },
        { "name": "Hackathon Winner", "icon": "TbTrophy" },
        { "name": "Merit Recognition", "icon": "TbStar" }
      ]
    },
    "languages": ["English (Native)", "Hindi (Fluent)", "Marathi (Fluent)", "German (Intermediate)", "Marwari (Conversational)"],
    "education": ["B.S. Mechanical Engineering", "Minor Computer Science", "Minor Mathematics", "Washington State University"],
    "strengths": ["Maximizer", "Relator", "Arranger", "Harmony", "Empathy"],
    "content": "Creative technologist with extensive experience in human-computer interaction, autonomous vehicle development, and advanced manufacturing systems. Passionate about bridging the gap between complex technology and intuitive user experiences."
  }
};
