// Tags data aggregated from all content files
// Auto-generated by scripts/generate-portfolio-data.js
// Do not edit manually - edit tags in individual content files instead

export const tagsData = {
  "team": [
    {
      "name": "Team Building",
      "icon": "TbUsersPlus"
    },
    {
      "name": "Leadership Development",
      "icon": "TbUserShield"
    }
  ],
  "project_management": [
    {
      "name": "Google Suite",
      "icon": "SiGoogle"
    }
  ],
  "technical": [
    {
      "name": "Python",
      "icon": "SiPython"
    },
    {
      "name": "React",
      "icon": "SiReact"
    },
    {
      "name": "C++",
      "icon": "SiCplusplus"
    },
    {
      "name": "SolidWorks",
      "icon": "SiSolidworks"
    }
  ],
  "experience": [
    {
      "name": "User Experience Design",
      "icon": "TbUserHeart"
    },
    {
      "name": "Autonomous Vehicles",
      "icon": "TbCar"
    },
    {
      "name": "Hardware Development",
      "icon": "TbCircuitCell"
    }
  ],
  "research": [
    {
      "name": "Innovation",
      "icon": "TbBulb"
    }
  ]
};
